//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/VideoPlayer/PlaybackControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlaybackControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlaybackControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlaybackControls"",
    ""maps"": [
        {
            ""name"": ""Playback"",
            ""id"": ""c49fbeeb-6a54-4b4b-a645-5d213d4d5a9e"",
            ""actions"": [
                {
                    ""name"": ""PlayPause"",
                    ""type"": ""Button"",
                    ""id"": ""8c945dc8-e39a-4353-8956-7ab4e223f64d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""865bda52-ab3f-4671-b322-1efada2fcc5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward"",
                    ""type"": ""Button"",
                    ""id"": ""404949bf-9cec-4d0d-82fd-f0a8d87638f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b2a4bd49-f968-442f-89d7-0a4386b253cd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4e35fd2-0a67-4ccf-b64e-7245585f8a7c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8370f119-75a1-4b04-a09c-de3333214689"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Playback
        m_Playback = asset.FindActionMap("Playback", throwIfNotFound: true);
        m_Playback_PlayPause = m_Playback.FindAction("PlayPause", throwIfNotFound: true);
        m_Playback_Forward = m_Playback.FindAction("Forward", throwIfNotFound: true);
        m_Playback_Backward = m_Playback.FindAction("Backward", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Playback
    private readonly InputActionMap m_Playback;
    private List<IPlaybackActions> m_PlaybackActionsCallbackInterfaces = new List<IPlaybackActions>();
    private readonly InputAction m_Playback_PlayPause;
    private readonly InputAction m_Playback_Forward;
    private readonly InputAction m_Playback_Backward;
    public struct PlaybackActions
    {
        private @PlaybackControls m_Wrapper;
        public PlaybackActions(@PlaybackControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayPause => m_Wrapper.m_Playback_PlayPause;
        public InputAction @Forward => m_Wrapper.m_Playback_Forward;
        public InputAction @Backward => m_Wrapper.m_Playback_Backward;
        public InputActionMap Get() { return m_Wrapper.m_Playback; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlaybackActions set) { return set.Get(); }
        public void AddCallbacks(IPlaybackActions instance)
        {
            if (instance == null || m_Wrapper.m_PlaybackActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlaybackActionsCallbackInterfaces.Add(instance);
            @PlayPause.started += instance.OnPlayPause;
            @PlayPause.performed += instance.OnPlayPause;
            @PlayPause.canceled += instance.OnPlayPause;
            @Forward.started += instance.OnForward;
            @Forward.performed += instance.OnForward;
            @Forward.canceled += instance.OnForward;
            @Backward.started += instance.OnBackward;
            @Backward.performed += instance.OnBackward;
            @Backward.canceled += instance.OnBackward;
        }

        private void UnregisterCallbacks(IPlaybackActions instance)
        {
            @PlayPause.started -= instance.OnPlayPause;
            @PlayPause.performed -= instance.OnPlayPause;
            @PlayPause.canceled -= instance.OnPlayPause;
            @Forward.started -= instance.OnForward;
            @Forward.performed -= instance.OnForward;
            @Forward.canceled -= instance.OnForward;
            @Backward.started -= instance.OnBackward;
            @Backward.performed -= instance.OnBackward;
            @Backward.canceled -= instance.OnBackward;
        }

        public void RemoveCallbacks(IPlaybackActions instance)
        {
            if (m_Wrapper.m_PlaybackActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlaybackActions instance)
        {
            foreach (var item in m_Wrapper.m_PlaybackActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlaybackActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlaybackActions @Playback => new PlaybackActions(this);
    public interface IPlaybackActions
    {
        void OnPlayPause(InputAction.CallbackContext context);
        void OnForward(InputAction.CallbackContext context);
        void OnBackward(InputAction.CallbackContext context);
    }
}
